// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportFederationsAccounting.Data;

#nullable disable

namespace SportFederationsAccounting.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506104041_Add_TemplatesAndMappings")]
    partial class Add_TemplatesAndMappings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.AccreditationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AccreditationStatuses");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.ContactPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("FederationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FederationId");

                    b.ToTable("ContactPersons");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.Federation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AccreditationEndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AccreditationStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FederationStateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("INN")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OGRN")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SportTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccreditationStatusId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FederationStateId");

                    b.HasIndex("SportTypeId");

                    b.ToTable("Federations");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.FederationState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FederationStates");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.SportType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SportTypes");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.ContactPerson", b =>
                {
                    b.HasOne("SportFederationsAccounting.Core.Models.Federation", "Federation")
                        .WithMany("ContactPersons")
                        .HasForeignKey("FederationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Federation");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.Federation", b =>
                {
                    b.HasOne("SportFederationsAccounting.Core.Models.AccreditationStatus", "AccreditationStatus")
                        .WithMany()
                        .HasForeignKey("AccreditationStatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportFederationsAccounting.Core.Models.FederationState", "FederationState")
                        .WithMany()
                        .HasForeignKey("FederationStateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SportFederationsAccounting.Core.Models.SportType", "SportType")
                        .WithMany()
                        .HasForeignKey("SportTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AccreditationStatus");

                    b.Navigation("FederationState");

                    b.Navigation("SportType");
                });

            modelBuilder.Entity("SportFederationsAccounting.Core.Models.Federation", b =>
                {
                    b.Navigation("ContactPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
